# Generated by Django 4.2.7 on 2023-11-20 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimencion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('isRadio', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('departamento', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('oferta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gastos_comunes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disposicon', models.CharField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caracteristica', models.ManyToManyField(to='propiedades.caracteristica')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=2400, null=True)),
            ],
            options={
                'verbose_name': 'TipoInmueble',
                'verbose_name_plural': 'TipoInmuebles',
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('inmueble_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedades.inmueble')),
                ('superficie_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superficie_inmmuebele', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anio_construccion', models.PositiveIntegerField(blank=True, default=0)),
                ('dormitorios', models.PositiveIntegerField(blank=True, default=0)),
                ('banios', models.PositiveIntegerField(blank=True, default=0)),
                ('parqueos', models.PositiveIntegerField(blank=True, default=0)),
                ('plantas', models.PositiveIntegerField(blank=True, default=0)),
            ],
            bases=('propiedades.inmueble',),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('inmueble_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedades.inmueble')),
                ('superficie_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anio_construccion', models.PositiveIntegerField(blank=True, default=0)),
                ('dormitorios', models.PositiveIntegerField(blank=True, default=0)),
                ('banios', models.PositiveIntegerField(blank=True, default=0)),
                ('parqueos', models.PositiveIntegerField(blank=True, default=0)),
                ('piso', models.PositiveIntegerField(blank=True, default=0)),
                ('cantidad_pisos', models.PositiveIntegerField(blank=True, default=0)),
            ],
            bases=('propiedades.inmueble',),
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('inmueble_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='propiedades.inmueble')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('propiedades.inmueble',),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, max_length=2400, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_zona', to='propiedades.area')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_zona', to='propiedades.ciudad')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_puntos', to='propiedades.area')),
            ],
            options={
                'verbose_name': 'Punto',
                'verbose_name_plural': 'Puntos',
            },
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_inmueble', to='propiedades.tipoinmueble'),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=350)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_inmueble', to='propiedades.inmueble')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_inmueble_character', to='propiedades.tipoinmueble'),
        ),
        migrations.AddField(
            model_name='area',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ubicacion', to='propiedades.inmueble'),
        ),
    ]
