# Generated by Django 4.2.7 on 2023-11-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristica',
            options={'verbose_name': 'Caracteristica', 'verbose_name_plural': 'Caracteristicas'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.RemoveField(
            model_name='zona',
            name='ciudad',
        ),
    ]
