# Generated by Django 4.2.7 on 2023-11-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_inmueble_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='gastos_comunes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='oferta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
