# Generated by Django 4.2.7 on 2023-11-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_alter_inmueble_gastos_comunes_alter_inmueble_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='disposicon',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='disposicion',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='gastos_comunes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
