# Generated by Django 4.2.7 on 2023-11-20 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, max_length=2400, null=True)),
            ],
            options={
                'verbose_name': 'TipoOferta',
                'verbose_name_plural': 'TipoOferas',
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=2400, null=True)),
                ('seoUrl', models.URLField(max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.inmueble')),
                ('tipo_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.tipooferta')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.zona')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
    ]
