# Generated by Django 4.2.7 on 2023-11-20 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='zona',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
