# Generated by Django 4.2.7 on 2023-11-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_remove_anuncio_zona_anuncio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='seoUrl',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
